[package]
name = "chat"
version = "0.1.0"
authors = ["jasilven <jasilven@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.34"
async-std = {version= "1.7", features= ["unstable", "attributes"]}
chrono = "0.4.19"
rand = "0.7.3"
